# Generated by Django 3.2.1 on 2021-05-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='firs_tname',
            new_name='first_name',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
