# Generated by Django 3.1.2 on 2021-07-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommapp', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
