# Generated by Django 3.1.2 on 2021-07-31 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommapp', '0009_auto_20210730_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
